### PR TITLE
C05_P01 C05_P02 - Chapter 5 solutions (partial)

### PR DESCRIPTION
**Pull request by bandarji**
Solutions to the first two Chapter 5 problems.

### CODE REVIEW

**Review by brycedrennan — CHANGES_REQUESTED** [review]
Thanks for these contributions.  We cannot have the questions in this code repo, only the solutions. Please remove the readme as well as comments containing the questions.

**Comment by bandarji** [comment]
Updated PR: dropped README and all book content.

**Comment by brycedrennan** [comment]
Great - thank you! 

Would you prefer to go through feedback back-and-forth or just have us accept this as is?  For example, it would be nice to have associated tests for these functions.

**Comment by bandarji** [comment]
If you accept this and close the PR, I'll revisit and write up tests. I shall also examine another chapter. Thanks!

**Review by brycedrennan — APPROVED** [review]

**Pull request merged**
