### PR TITLE
C04_P02: Simpler solution

### PR DESCRIPTION
**Pull request by cjoshmartin**
Saw this solution on geeksforgeeks and taught it was easier to understand. https://www.geeksforgeeks.org/sorted-array-to-balanced-bst/

### CODE REVIEW

**Review by brycedrennan — CHANGES_REQUESTED** [review]
Thanks, I like the idea, but it seems to produce different results than the existing solution. Can you figure out whats going on?

**Comment by cjoshmartin** [comment]
@brycedrennan What do you mean? How do you tell?

**Comment by brycedrennan** [comment]
I ran the code at the bottom of the file without your changes and with them and the output was different.

**Comment by brycedrennan** [comment]
Happy to re-open if there are any updates.

**Pull request closed without merging**
