### PR TITLE
fixed one_edit_insert function and added one more test case

### PR DESCRIPTION
**Pull request by bravominski**
Issue with Chapter1 Q5. OneAway.py

There seems to be a bug in one_edit_insert function.

test case with input ('paleabc', 'pleabc', True) won't pass with current implementation

current implementation

```
def one_edit_insert(s1, s2):
    edited = False
    i, j = 0, 0
    while i < len(s1) and j < len(s2):
        if s1[i] != s2[j]:
            if edited:
                return False
            edited = True
            i += 1
        i += 1
        j += 1
    return True
```

and after the second if statement, after change 'edited' to True,
it should be j += 1, not i and also need to add continue after that.
So it would work with 

```
def one_edit_insert(s1, s2):
    edited = False
    i, j = 0, 0
    while i < len(s1) and j < len(s2):
        if s1[i] != s2[j]:
            if edited:
                return False
            edited = True
            j += 1
            continue
        i += 1
        j += 1
    return True
```

Because j is a pointer index for the longer string among two, it should be j that is updated when there is a first mismatch.
Also once j is updated, we cannot update i and j again yet since we need to check parity at the current position again with only j moved forward by 1

### CODE REVIEW

**Comment by mmermerkaya** [comment]
Thanks for the fix!

Instead of `continue`, I think it's better if you used an `else` statement. The solution in the book uses `else` too.

**Comment by jrusev** [comment]
👍  This will fix it. Here are some more tests:

```
data = [
    ('a', 'b', True),
    ('', 'd', True),
    ('d', 'de', True),
    ('pale', 'pale', True),
    ('pale', 'ple', True),
    ('ple', 'pale', True),
    ('pale', 'bale', True),
    ('pale', 'bake', False),
    ('pale', 'pse', False),
    ('ples', 'pales', True),
    ('pale', 'pas', False),
    ('pas', 'pale', False),
    ('pale', 'pkle', True),
    ('pkle', 'pable', False),
    ('pal', 'palks', False),
    ('palks', 'pal', False)
]
```

BTW, I was working on a different problem today called [Word Chains](https://www.4clojure.com/problem/82), and I needed a method to do exactly what this problem requires, so I found a more concise way to solve it:

```python
def one_away(s1, s2):
    h1, t1 = s1[:1], s1[1:]
    h2, t2 = s2[:1], s2[1:]
    return t1 == t2 or (one_away(t1, t2) if h1 == h2 else t1 == s2 or t2 == s1)
```

You can test it with the test data above.

**Comment by bravominski** [comment]
Got it :) 

I will update this pull request after addressing comments!

**Comment by bravominski** [comment]
@jrusev I really like the solution you have, but just one question before I try to apply it.

If the purpose of this open source project is to help ppl out understanding the coding challenges better, I assume readability should also be considered. If it takes them much shorter time to understand a longer code, than I guess we better choose that.

Also it sounds like this group is inclined to follow the solutions on the book(which I personally think is quite easy to understand even when coded into Python). 

Would you still like me to apply your algorithm into the answer? @mmermerkaya Your comments will be also really appreciated!(or rather you decide haha)

**Comment by bravominski** [comment]
@mmermerkaya addressed your comments, plz let me know if you would prefer having @jrusev 's more concise logic into this solution!

**Comment by jrusev** [comment]
@bravominski I also think it may be more helpful to stick to the solutions offered in the book, written of course in the most pythonic way. This way, the repo can be used as a sort of a rosetta stone - the same algorithm expressed in different languages.

I am not sure what is the place of alternative solutions. Either include them as a separate file, or not include them at all. In general these should be rare cases as the solutions in the book are generally the optimal ones. So it's your call in this case :)

**Comment by bravominski** [comment]
@jrusev cool, I somewhat agree that solutions here should remain as readable and easy to understand as possible. So my call will be to go with longer but easier one. @mmermerkaya  if you're okay with that I guess this one's good to go

**Comment by jrusev** [comment]
👍

**Comment by mmermerkaya** [comment]
Looks good to me :)

**Pull request merged**
