### PR TITLE
feature(C04_P06): added tests

### PR DESCRIPTION
**Pull request by humming-an**
Added tests to check the 'in order' next node for problem p06 in chapter 4.

### CODE REVIEW

**Comment by humming-an** [comment]
fixed lint

**Comment by brycedrennan** [comment]
Thanks @humming-an this looks good.

Lets move this to its own testing function. like this: 

```python
def test_in_order_successor():
    bst = BinarySearchTree()
    bst.insert(20)
    bst.insert(9)
    bst.insert(25)
    bst.insert(5)
    bst.insert(12)
    bst.insert(11)
    bst.insert(14)

    # Test all nodes
    inputs = [5, 9, 11, 12, 14, 20, 25]
    outputs = inputs[1:]
    outputs.append(None)

    for x, y in zip(inputs, outputs):
        test = bst.get_node(x)
        succ = in_order_successor(test)
        if succ is not None:
            assert succ.key == y
        else:
            assert succ == y
```
I can wait for you to make this change or just do it for you. Let me know-

**Comment by humming-an** [comment]
@brycedrennan - thanks for the suggestion. I have added its own test function now.

**Review by brycedrennan — APPROVED** [review]

**Comment by brycedrennan** [comment]
great work - thanks!

**Pull request merged**
